- src/ConstructionBase.jl
- test/runtests.jl
@tkf @rafaqz some API questions:
* Shall we change the signature of `setproperties`? Currently it is `setproperties(obj, patch)`. But maybe `setproperties(obj; kw...)` is more convenient?
* Shall we export `constructor_of`? Shall we rename it into e.g. `positional_constructor`?
> Decide API for setproperties and constructorof

- README.md
- src/ConstructionBase.jl
Current `setproperties` spec indicates that users need to support arbitrary `patch` object.  Doing this in general requires unnecessary reflection-based code (e.g., you don't need to use `fieldnames` for `NamedTuple`s as you can just dispatch on `::NamedTuple{names}`).  Instead, why not specify that it is only required to overload `setproperties(::MyType, ::NamedTuple)`?  We may also need to support other patch types in the future (e.g., `Dict`).  Restricting the patch type would help it.
> Restrict patch to NamedTuple

- src/ConstructionBase.jl
> specify setproperties more precisely #11

- src/ConstructionBase.jl
- test/runtests.jl
> Type-stable constructorof(::Type{<:NamedTuple})(args...)

- src/ConstructionBase.jl
- test/runtests.jl
I started implementing this because I remember doing [something similer in Kaleido.jl](https://github.com/tkf/Kaleido.jl/blob/080406ffe05aa47770cf6294610196447b0c11fa/src/base.jl#L40-L42) but then realized that what I did in Kaleido.jl is a bit differnt from actual `constructorof` spec. So, this PR is not driven by a real need at this point.  However, since `Tuple` and `NamedTuple` are so basic that I think it makes sense to support this.  What do you think?
(One potential benefit was that we can remove `setproperties(::NamedTuple, ::NamedTuple)` with this PR. But the inference test failed with the generic fallback so that's no go.)
> Define constructorof for Tuple and NamedTuple?

- docs/src/index.md
- src/ConstructionBase.jl
- src/constructorof.md
- src/setproperties.md
Since most of the code in this repo will be documentation, how about putting docstring in separated markdown files? It's easier to edit and review.
> Load docstrings from markdown files

- src/ConstructionBase.jl
- test/runtests.jl
Also the body of `@generated setproperties(...)` was impure as it was responsible for throwing the error. Not sure if this is a problem in practice, but it is forbidden in theory.
> Improve setproperties error message

- docs/Project.toml
- docs/src/index.md
- src/constructorof.md
This probably is too opinionated to be in the official documentation, but I thought is worth a shot.  What do you think?
If you want to look at a semi-rendered version, see:
https://github.com/tkf/ConstructionBase.jl/blob/tips/docs/src/index.md#tips-for-designing-typesid-type-tips
> Add a section "Tips for designing types"

- src/ConstructionBase.jl
- src/constructorof.md
- src/getproperties.md
- src/setproperties.md
- test/runtests.jl
Adds a `getproperties` method, primarily to handle construction of objects with undefined fields, but also more broadly useful for getting object fields as a `NamedTuple`. See #36.
> add getproperties method

- Project.toml
- src/ConstructionBase.jl
- src/nonstandard.jl
- test/runtests.jl
Some `constructorof` methods for  Base and LinearAlgebra array wrappers, as discussed in #34.
Probably we shouldn't add a constructor for `Tridiagonal` because of the undef field - seems it would break Accessors.jl/Flatten.jl etc? 
I'm not sure what to do about it long-term, possibly a PR to base using `nothing` instead of `undef` for `du2`? How many other structs have undef fields?
Closes #34
There are probably a bunch of other base objects that need `constuctorof` methods. Feel free to list more for me to add to this PR.
> WIP add constructors for base array wrappers

- .github/workflows/TagBot.yml
- docs/src/index.md
- src/constructorof.md
This should fix the lack of tagging on recent version bumps.
See #42
> update TagBot script

- src/constructorof.md
- src/functions.jl
- test/runtests.jl
Switch to checking that the name is gensym and there is no constructor defined, as the heuristic for identifying anonymous functions, so that we don't call `new` on custom function structs when there is another constructor that could be called.
> check gensym name to avoid new on user defined Function objects

- src/nonstandard.jl
Using `view` for constructing `SubArray` introduces bugs where `view` is customised for some types of `AbstractArray`. This is less likely to happen with the `SubArray` constructor.
> bugfix SubArray

- .github/workflows/Downstream.yml
Run tests of the most popular (thousands of users, hundreds of dependents) dependent packages that heavily rely on ConstructionBase.
Julia 1.6 (LTS), 1 latest, and nightly.
yml file originally taken from https://github.com/SciML/SciMLBase.jl/blob/master/.github/workflows/Downstream.yml.
> add downstream CI

- src/ConstructionBase.jl
- test/runtests.jl
A common case in the wild: `StructArray{Tuple{...}}`. Now, `getproperties` automatically supports this case and returns a tuple. The `setproperties` fallback isn't changed: by necessity, such objects define custom `propertynames`, so they require custom `setproperties` anyway.
> support numeric propertynames

- Project.toml
- ext/IntervalSetsExt.jl
- ext/StaticArraysExt.jl
- test/runtests.jl
Would automatically support staticarrays and intervals on Julia 1.9+, nothing changes on earlier versions.
Extensions follow https://pkgdocs.julialang.org/dev/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions).
Integration implementations themselves are copied directly from https://github.com/JuliaObjects/ConstructionBaseExtras.jl. `ConstructionBaseExtras` would become obsolete on 1.9+.
Don't merge yet: Registrator hasn't been updated to support extensions.
> add intervalsets and staticarrays support

- src/setproperties.md
Just corrects a typo in the docstring of setproperties.
> Fixed simple typo.

- Project.toml
- ext/ConstructionBaseIntervalSetsExt.jl
- ext/ConstructionBaseStaticArraysExt.jl
- This prevents clash of extension names.
- Currently, clashes with Accessors.jl.
- And clashing names throw fatal errors while building sysimages.
- See: https://github.com/JuliaObjects/Accessors.jl/pull/104
> Prefix parent package name to extension names

- Project.toml
- src/nonstandard.jl
- test/runtests.jl
`propertynames` is overloaded for `LinearAlgebra.Cholesky`, hence it requires impl of `setproperties`. I've made an attempt at that in this PR:)
> Implementation of `setproperties` for `LinearAlgebra.Cholesky`

- Project.toml
- src/ConstructionBase.jl
We found that for really large tuples the Julia compiler would give up on constfolding the comparison leading to a runtime check. Tuples of symbols are `===` so this change makes it easier for the compiler to inline.
> Use strict equality for comparing properties

- src/ConstructionBase.jl
> use a tuple instead of Ref in broadcasts

- Project.toml
- ext/ConstructionBaseLinearAlgebraExt.jl
- src/ConstructionBase.jl
- src/nonstandard.jl
- test/runtests.jl
should make the package dependency free on julia > 1.9. motivated by [JuliaFolds2/Trand](https://github.com/JuliaFolds2/Transducers.jl/issues/35)
> add LinearAlgebraExt

- Project.toml
- src/ConstructionBase.jl
ConstructionBase doesn't depend on anything (apart from LinearAlgebra currently), so it can't trigger the circular dependency issue. It's completely safe to make LinearAlgebra a weak dependency on all Julia versions that support weak dependencies.
On the contrary, if ConstructionBase keeps LinearAlgebra as a direct dependency, then packages that depend on ConstructionBase and decide to make LinearAlgebra a weak dependency (e.g. Accessors) will run into the circular dependency issue. So a direct dependency on LinearAlgebra in ConstructionBase holds back large parts of the ecosystem.
> Make LinearAlgebra a weak dependency
